### ISSUE TITLE
exp error

### ISSUE THREAD

**Issue by kambire** [fIyingPhoenix/TrionControlPanel#15]
Seems like there is an experience bug. For example, when completing a quest it says "1000xp" but only rewards 200xp. As an example, I tried disabling modules to see if the error persisted and it does. I don't understand why this is happening. When the server is turned off and restarted, everything works fine for a few minutes and then the problem comes back. The same thing happens with mob experience. For example, it starts giving 100 experience and then after a few minutes it drops to 20. We don't know why this is happening. This error occurs with AzerothCore, we haven't tested with any other server.

**Comment by fIyingPhoenix** [comment]
This is not Trion Related. You can get help on the discord server.
