### ISSUE TITLE
error inserting mysql address

### ISSUE THREAD

**Issue by jhoancito** [fIyingPhoenix/TrionControlPanel#3]
error when inserting mysql address I put the address does not connect me I get an error

![Captura](https://user-images.githubusercontent.com/85852080/203454536-53be95bb-4814-41d3-bed1-ade68b79d728.PNG)

![1](https://user-images.githubusercontent.com/85852080/203454783-f0fd9b41-36ee-4436-a066-c8e80acae1b2.PNG)

**Comment by fIyingPhoenix** [comment]
I need more Info. do you have a custom my.ini? 
i didn't try it on 5.6 bcs its dated and out of support. try use the 8.* form the core and transfer your data there. 
"Unable to connect" its more your user pass and host is wrogn
